#!/usr/bin/env python3
"""Generate exact filtered MIMIC-CXR JPG download list for C4 trauma cohort.

Input: c4_cxr_dicom_layers.csv generated by link_c4_cxr.py.
Default layer: L3_icu_window_cxr.

Does NOT download anything.
"""
import csv
import json
import os

PROJECT_ROOT = "/home/vanila/code/EHR-Predict"
OUT_DIR = os.path.join(PROJECT_ROOT, "data dicision", "trauma cohort", "cxr_linkage", "download_prep")
DICOM_LAYER_CSV = os.path.join(PROJECT_ROOT, "data dicision", "trauma cohort", "cxr_linkage", "c4_cxr_dicom_layers.csv")
PHYSIONET_BASE = "https://physionet.org/files/mimic-cxr-jpg/2.0.0/"
ESTIMATED_JPG_SIZE_MB = 1.0
DEFAULT_LAYER = "L3_icu_window_cxr"


def image_url(subject_id, study_id, dicom_id):
    return f"{PHYSIONET_BASE}files/p{subject_id[:2]}/p{subject_id}/s{study_id}/{dicom_id}.jpg"


def main(layer=DEFAULT_LAYER):
    os.makedirs(OUT_DIR, exist_ok=True)
    rows = []
    with open(DICOM_LAYER_CSV, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        if layer not in reader.fieldnames:
            raise ValueError(f"Unknown layer {layer}; available columns: {reader.fieldnames}")
        for row in reader:
            if row[layer] == "1" and row.get("dicom_id"):
                rows.append(row)

    # Deduplicate URL/image rows; same image can theoretically match multiple stays under same HADM.
    urls = []
    seen = set()
    hadms = set()
    subjects = set()
    studies = set()
    for row in rows:
        url = image_url(row["subject_id"], row["study_id"], row["dicom_id"])
        if url in seen:
            continue
        seen.add(url)
        urls.append(url)
        hadms.add(row["hadm_id"])
        subjects.add(row["subject_id"])
        studies.add(row["study_id"])

    safe_layer = layer.replace("_cxr", "")
    list_path = os.path.join(OUT_DIR, f"c4_cxr_download_list_{safe_layer}.txt")
    with open(list_path, "w", encoding="utf-8") as f:
        for url in urls:
            f.write(url + "\n")

    # Stable default symlink/copy target used by docs.
    default_list_path = os.path.join(OUT_DIR, "c4_cxr_download_list.txt")
    with open(default_list_path, "w", encoding="utf-8") as f:
        for url in urls:
            f.write(url + "\n")

    summary = {
        "cohort": "C4",
        "layer": layer,
        "hadm_count": len(hadms),
        "subject_count": len(subjects),
        "study_count": len(studies),
        "file_count": len(urls),
        "estimated_total_size_mb": round(len(urls) * ESTIMATED_JPG_SIZE_MB, 1),
        "estimated_total_size_gb": round(len(urls) * ESTIMATED_JPG_SIZE_MB / 1024, 1),
        "output_list": list_path,
        "default_output_list": default_list_path,
        "source_dicom_layer_csv": DICOM_LAYER_CSV,
        "download_command": (
            f"wget -c --user <PHYSIONET_USER> --password <PHYSIONET_PASS> "
            f"-i '{default_list_path}' -P /mnt/d/Data/mimic-cxr-jpg-c4/"
        ),
        "note": "Exact image-row filter from c4_cxr_dicom_layers.csv; does not include unrelated CXR from same subject.",
    }
    summary_path = os.path.join(OUT_DIR, "c4_cxr_download_summary.json")
    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
